[package]
name = "quic-rpc-derive"
version = "0.11.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
quic-rpc = { version = "0.11", path = ".." }

[dev-dependencies]
derive_more = "1.0.0-beta.6"
serde = { version = "1.0.203", features = ["serde_derive"] }
trybuild = "1.0.96"
